In [1]:
import numpy as np

In [2]:
vetor = np.array([0,1,2,3,4,5,6,7,9])

In [3]:
print(vetor)

[0 1 2 3 4 5 6 7 9]


In [4]:
type(vetor)

numpy.ndarray

In [2]:
import pandas as pd

In [4]:
obj = pd.Series([67,78,-56,13])

In [5]:
obj

0    67
1    78
2   -56
3    13
dtype: int64

In [6]:
type(obj)

pandas.core.series.Series

In [7]:
obj.values

array([ 67,  78, -56,  13], dtype=int64)

In [8]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
obj2 = pd.Series([67,78,-56,13], index = ['a','b','c','d'])

In [11]:
obj2

a    67
b    78
c   -56
d    13
dtype: int64

In [12]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [13]:
obj2.values

array([ 67,  78, -56,  13], dtype=int64)

In [14]:
obj2[obj2 > 3]

a    67
b    78
d    13
dtype: int64

In [15]:
obj2['b']

78

In [16]:
'd' in obj2

True

In [34]:
dict = {'Futebol':5200,'Tenis':120,'Natação':698,'Volleyball':1550}

In [35]:
obj3 = pd.Series(dict)

In [36]:
obj3

Futebol       5200
Tenis          120
Natação        698
Volleyball    1550
dtype: int64

In [21]:
type(obj3)

pandas.core.series.Series

In [27]:
esportes = ['Futebol', 'Tenis', 'Natação','Baskteball']

In [28]:
obj4 = pd.Series(dict, index = esportes)

In [29]:
obj4

Futebol       5200.0
Tenis          120.0
Natação        698.0
Baskteball       NaN
dtype: float64

In [30]:
pd.isnull(obj4)

Futebol       False
Tenis         False
Natação       False
Baskteball     True
dtype: bool

In [31]:
pd.notnull(obj4)

Futebol        True
Tenis          True
Natação        True
Baskteball    False
dtype: bool

In [37]:
obj3 + obj4

Baskteball        NaN
Futebol       10400.0
Natação        1396.0
Tenis           240.0
Volleyball        NaN
dtype: float64

In [38]:
obj4.name = "população"

In [39]:
obj4.index.name = "esporte"

In [40]:
obj4

esporte
Futebol       5200.0
Tenis          120.0
Natação        698.0
Baskteball       NaN
Name: população, dtype: float64